version: 2

updates:
  - package-ecosystem: "npm"
    directory: "modules/apps/ip-search/ip-search-web/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "glob-parent"