version: 2

updates:
  - package-ecosystem: "npm"
    directory: "modules/apps/ip-search/ip-search-web/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    labels:
      - devDependencies
    versioning-strategy: increase
    ignore:
      - dependency-name: "glob-parent"